name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-base-docker-image-generic.yml@0c71f00e40f49d9bbfc59acb821387e0751ab4d2
    with:
      dockerImage: powsybl/java-dynawo
      dockerUsername: powsyblci
      eventOrganizations: gridsuite
      eventType: java_dynawo_updated
    secrets:
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
